(function(){


var ideaGroupNames = {
    "administrative_ideas": "Administrative",
    "innovativeness_ideas": "Innovativeness",
    "religious_ideas": "Religious",
    "spy_ideas": "Spy",
    "dynasty0": "Dynastic",
    "influence_ideas": "Influence",
    "offensive_ideas": "Offensive",
    "defensive_ideas": "Defensive",
    "trade_ideas": "Trade",
    "economic_ideas": "Economic",
    "exploration_ideas": "Exploration",
    "maritime_ideas": "Maritime",
    "quality_ideas": "Quality",
    "quantity_ideas": "Quantity",
    "expansion_ideas": "Expansion",
    "humanist_ideas": "Humanist",
    "katholisch0": "Catholic",
    "protestant0": "Protestant",
    "reformiert0": "Reformed",
    "orthodox0": "Orthodox",
    "islam0": "Sunni",
    "tengri0": "Tengri",
    "hindu0": "Hindu",
    "confuci0": "Confucian",
    "budda0": "Buddhist",
    "norse0": "Norse",
    "shinto0": "Shinto",
    "cathar0": "Cathar",
    "coptic0": "Coptic",
    "romuva0": "Romuva",
    "suomi0": "Suomi",
    "jew0": "Jewish",
    "slav0": "Slav",
    "helle0": "Hellanistic",
    "mane0": "Manichean",
    "animist0": "Anamist",
    "feti0": "Fetishist",
    "zoro0": "Zoroastrianism",
    "ancli0": "Anglican",
    "nahu0": "Nahuatl",
    "mesoam0": "Mesoamerican",
    "inti0": "Inti",
    "tote0": "Totemism",
    "shia0": "Shia",
    "ibadi0": "Ibadi",
    "hussite0": "Hussite",
    "justiz0": "Judicial",
    "entwicklung0": "Development",
    "gesundheit0": "Health",
    "monarchie0": "Monarchy",
    "republik0": "Republic",
    "aristo0": "Theocracy",
    "diktatur0": "Dictatorship",
    "horde0": "Horde",
    "gross0": "Heavy ship",
    "galle0": "Galley",
    "handel0": "Light ship",
    "kolonialimperium0": "Colonial empire",
    "assimilation0": "Assimilation",
    "gesellschaft0": "Society",
    "propaganda0": "Propaganda",
    "flottenbasis0": "Fleet base",
    "nationalismus0": "Nationalism",
    "konigreich0": "Imperial ambition",
    "imperialismus0": "Imperial",
    "generalstab0": "General staff",
    "stehendesheer0": "Standing army",
    "soldnerheer0": "Mercenary army",
    "wehrpflicht0": "Conscription",
    "waffenqualitat0": "Weapon quality",
    "festung0": "Fortress",
    "kriegsproduktion0": "War production",
    "staatsverwaltung0": "State administration",
    "zentra0": "Centralism",
    "dezentra0": "Decentralism",
    "formation0": "Tactics",
    "militarismus0": "Militarism",
    "shock0": "Shock",
    "fire0": "Fire",
}

var bonusNames = {
    "adm_tech_cost_modifier" : "Admin tech cost modifier",
  "admiral_cost": "Admiral cost",
  "advisor_cost": "Advisor cost",
  "advisor_pool": "Advisor pool",
  "ae_impact": "Aggressive expansion impact",
  "allowed_marine_fraction": "Marine fraction",
  "army_tradition": "Army tradition",
  "artillery_bonus_vs_fort": "Artillery bonus vs fort",
  "artillery_cost": "Artillery cost",
  "artillery_power": "Artillery power",
  "autonomy_change_time": "Autonomy change time",
  "backrow_artillery_damage": "Backrow artillery damage",
  "blockade_efficiency": "Blockade efficiency",
  "build_cost": "Build cost",
  "build_time": "Build time",
  "can_fabricate_for_vassals": "Can fabricate for vassals",
  "caravan_power": "Caravan power",
  "cav_to_inf_ratio": "Cavalry to infantry ratio",
  "cavalry_cost": "Cavalry cost",
  "cavalry_flanking": "Cavalry flanking",
  "cavalry_power": "Cavalry power",
  "cb_on_overseas": "CB on overseas",
  "cb_on_primitives": "CB on primatives",
  "cb_on_religious_enemies": "CB on religious enemies",
  "church_power_modifier": "Church power modifier",
  "claim_duration": "Claim duration",
  "colonists": "Colonists",
  "core_creation": "Core creation cost",
  "culture_conversion_cost": "Culture conversion cost",
  "defensiveness": "Defensiveness",
  "development_cost": "Development cost",
  "devotion": "Devotion",
  "dip_tech_cost_modifier": "Diplo tech cost modifier",
  "diplomatic_annexation_cost": "Diplomatic annexation cost",
  "diplomatic_reputation": "Diplomatic reputation",
  "diplomatic_upkeep": "Diplomatic upkeep",
  "diplomats": "Diplomats",
  "discipline": "Discipline",
  "drill_decay_modifier": "Drill decay modifier",
  "drill_gain_modifier": "Drill gain modifier",
  "embargo_efficiency": "Embargo efficiency",
  "embracement_cost": "Institution embracement cost",
  "enemy_core_creation": "Enemy core creation cost",
  "enforce_religion_cost": "Enforce religionn cost",
  "expel_minorities_cost": "Expel minorities cost",
  "extra_manpower_at_religious_war": "Extra manpower at religious war",
  "female_advisor_chance": "Female advisor chance",
  "fire_damage": "Fire damage",
  "fire_damage_received": "Fire damage received",
  "fort_maintenance_modifier": "Fort maintenance modifier",
  "free_leader_pool": "Free leader pool",
  "galley_cost": "Galley cost",
  "galley_power": "Galley power",
  "garrison_size": "Garrison size",
  "global_autonomy": "Global_autonomy",
  "global_colonial_growth": "Global colonial growth",
  "global_garrison_growth": "Global garrison growth",
  "global_heretic_missionary_strength": "Missionary strength vs heretics",
  "global_institution_spread": "Global institution spread",
  "global_manpower": "Global Manpower",
  "global_manpower_modifier": "Global Manpower Modifier",
  "global_missionary_strength": "Missionary strength",
  "global_prov_trade_power_modifier": "Provincial trade power modifier",
  "global_regiment_cost": "Regiment cost",
  "global_regiment_recruit_speed": "Regiment recruit speed",
  "global_religious_conversion_resistance": "Religious conversion resistance",
  "global_sailors": "Global sailors",
  "global_sailors_modifier": "Global sailor modifier",
  "global_ship_cost": "Ship cost",
  "global_ship_recruit_speed": "Ship recruit speed",
  "global_ship_repair": "Ship repair",
  "global_ship_trade_power": "Ship trade power",
  "global_spy_defence": "Spy defence",
  "global_supply_limit_modifier": "Global supply limit modifier",
  "global_tariffs": "Tarrifs",
  "global_tax_modifier": "Tax",
  "global_trade_goods_size_modifier": "Goods Produced",
  "global_trade_power": "Global trade power",
  "global_unrest": "Global unrest",
  "governing_capacity": "Governing capacity",
  "governing_capacity_modifier": "Governing capacity modifier",
  "harmonization_speed": "Harmonization speed",
  "harsh_treatment_cost": "Harsh treatment cost",
  "heavy_ship_cost": "Heavy ship cost",
  "heavy_ship_power": "Heavy ship power",
  "heir_chance": "Heir chance",
  "horde_unity": "Horde unity",
  "hostile_attrition": "Hostile attrition",
  "idea_cost":"Idea cost",
  "imperial_authority": "Imperial authority modifier",
  "imperial_authority_value": "Imperial authority",
  "imperial_mandate": "Mandate",
  "improve_relation_modifier": "Improve relations modifier",
  "infantry_cost": "Infantry cost",
  "infantry_power": "Infantry power",
  "inflation_action_cost": "Reduce inflation cost reduction",
  "inflation_reduction": "Yearly inflation reduction",
  "innovativeness_gain": "Innovativeness gain",
  "institution_spread_from_true_faith": "Institution spread from true faith",
  "interest": "Interest",
  "land_attrition": "Land attrition",
  "land_forcelimit": "Land force limit",
  "land_forcelimit_modifier": "Land force limit modifier",
  "land_maintenance_modifier": "Land maintenance modifier",
  "land_morale": "Morale of armies",
  "leader_land_fire": "Land leader fire",
  "leader_land_manuever": "Land leader manuevar",
  "leader_land_shock": "Land leader shock",
  "leader_naval_fire": "Naval leader fire",
  "leader_naval_manuever": "Naval leader manuever",
  "leader_naval_shock": "Naval leader shock",
  "leader_siege": "Leader siege",
  "legitimacy": "Legitimacy",
  "liberty_desire_from_subject_development": "Liberty desire from subject development",
  "light_ship_cost": "Light ship cost",
  "light_ship_power": "Light ship power",
  "loot_amount": "Loot amount",
  "manpower_in_true_faith_provinces": "Manpower in true faith provinces",
  "manpower_recovery_speed": "Manpower recovery speed",
  "max_absolutism": "Maximum absolutism",
  "may_explore": "May explore",
  "may_perform_slave_raid": "May perform slave raid",
  "merc_maintenance_modifier": "Mercenary maintenance modifier",
  "mercenary_cost":"Mercenary cost",
  "mercenary_discipline":"Mercenary discipline",
  "mercenary_manpower":"Mercenary manpower",
  "merchants":"Merchants",
  "meritocracy":"Meritocracy",
  "mil_tech_cost_modifier":"Military tech cost modifier",
  "missionaries":"Missionaries",
  "missionary_maintenance_cost":"Missionary maintenance cost",
  "monarch_admin_power":"Monarch admin power",
  "monarch_diplomatic_power":"Monarch diplomatic power",
  "monarch_military_power":"Monarchy military power",
  "monthly_fervor_increase":"Monthly fervor increase",
  "monthly_militarized_society":"Monthly militarized society",
  "monthly_splendor":"Monthly splendor",
  "movement_speed":"Movement speed",
  "naval_attrition":"Naval attrition",
  "naval_forcelimit":"Naval forcelimit",
  "naval_forcelimit_modifier":"Naval forcelimit modifier",
  "naval_maintenance_modifier":"Naval maintenance modifier",
  "naval_morale":"Naval moralce",
  "navy_tradition":"Navy tradition",
  "num_accepted_cultures":"Number of accepted cultures",
  "papal_influence":"Papal influence",
  "prestige":"Prestige",
  "prestige_decay":"Prestige decay",
  "prestige_from_land":"Prestige from land",
  "privateer_efficiency":"Privateer efficiency",
  "production_efficiency":"Production efficiency",
  "promote_culture_cost": "Promote culture cost",
  "province_warscore_cost": "Province warscore cost",
  "range": "Colonial range",
  "raze_power_gain": "Razing power gain",
  "rebel_support_efficiency":"Rebel support efficiency",
  "recover_army_morale_speed":"Recover army morale speed",
  "recover_navy_morale_speed": "Recover navy morale speed",
  "reduced_liberty_desire": "Reduced libery desire",
  "reduced_stab_impacts": "Reduced stability impact from diplo",
  "reform_progress_growth": "Reform progress growth",
  "reinforce_cost_modifier":"Reinforce cost modifier",
  "reinforce_speed":"Reinforce speed",
  "relation_with_heretics":"Relation with heretics",
  "religious_unity": "Religious unity",
  "republican_tradition": "Republican tradition",
  "sailor_maintenance_modifer": "Sailor maintenance modifier",
  "sailors_recovery_speed": "Sailors recovery speed",
  "same_culture_advisor_cost": "Same culture advisor cost",
  "ship_durability":"Ship durability",
  "shock_damage":"Shock damage",
  "shock_damage_received":"Shock damage received",
  "siege_ability":"Siege ability",
  "siege_blockade_progress":"Siege blockade progress",
  "special_unit_forcelimit":"Special unit forcelimit",
  "spy_offence":"Spy offence",
  "stability_cost_modifier": "Stability cost modifier",
  "state_maintenance_modifier":"State maintenance modifier",
  "technology_cost":"Technology cost",
  "tolerance_heathen":"Tolerance of heathens",
  "tolerance_heretic":"Tolerance of heretics",
  "tolerance_own":"Tolerance of true faith",
  "trade_company_governing_cost":"Trade company governing cost",
  "trade_efficiency":"Trade efficiency",
  "trade_range_modifier":"Trade range modifier",
  "trade_steering":"Trade steering",
  "transport_cost":"Transport cost",
  "transport_power":"Transport power",
  "unjustified_demands":"Unjustified demands",
  "war_exhaustion":"War exhaustion",
  "war_exhaustion_cost": "War exhaustion cost",
  "war_taxes_cost_modifier":"War taxes cost",
  "warscore_cost_vs_other_religion": "Warscore cost vs other religions",
  "yearly_absolutism":"Yearly absolutism",
  "yearly_army_professionalism":"Yearly army professionalism",
  "yearly_corruption":"Yearly corruption",
  "yearly_harmony":"Yearly harmony",
  "yearly_patriarch_authority":"Yearly patriarch authority",
  "years_of_nationalism":"Years of nationalism"
}

window.replaceName = function(s){
    if(ideaGroupNames[s]){
        return ideaGroupNames[s];
    }
    if(bonusNames[s]){
        return bonusNames[s];
    }
    return s;
}
}())