const nameCache = {};
const urlCache = {};
(<any>window).urlCache = urlCache;
function getName(bonusName: string): string{
    return nameCache[bonusName];
}
function setName(bonusName: string, mappedBonusName: string): void{
    nameCache[bonusName] = mappedBonusName;
}
function hasName(bonusName: string): boolean{
    return nameCache[bonusName] !== undefined;
}

function getUrl(bonusName: string): string{
    return urlCache[bonusName];
}
function setUrl(bonusName: string, bonusUrl: string): void{
    urlCache[bonusName] = bonusUrl;
}
function hasUrl(bonusName: string): boolean{
    return urlCache[bonusName] !== undefined;
}

export function getBonusUrl(bonusName: string): string{
    if(hasUrl(bonusName)){return getUrl(bonusName)}
    var baseMapped = baseMap(bonusName);
    if(baseMapped){bonusName = baseMapped;}
    switch(bonusName){
        case "fort_maintenance_modifier":
			bonusName = "fort_maintenance";
			break;
        default:
            break;
    }
    var url = capitalise(bonusName);
    setUrl(bonusName, url);
    return url;
}

export function getBonusName(bonusName: string): string{
    if(hasName(bonusName)){return getName(bonusName)}
    var baseMapped = baseMap(bonusName);
    if(baseMapped){bonusName = baseMapped;}
    switch(bonusName){
        default:
            break;
    }
    var name = bonusName.split('_').map(capitalise).join(' ');
    setName(bonusName, name);
    return name;
}

export function displayBonusValue(bonusValue: any, bonusName: string): string {
	switch(bonusName.toLowerCase()){
		case "add_building":
		case "development_cost_over_25":
		case "extra_navytradition_heavy_ships":
		case "extra_navytradition_galley":
		case "extra_navytradition_light_ships":
		case "reduced_dev_malus":
		case "free_cardinal":
		case "can_fabricate_for_vassals":
		case "cb_on_overseas":
		case "cb_on_primitives":
		case "cb_on_religious_enemies":
		case "stand_interaktion":
		case "elective_monarchy_dip_buff":
		case "extra_manpower_at_religious_war":
		case "may_explore":
		case "may_perform_slave_raid":
		case "reduced_stab_impacts":
		case "morale_bonus_5_cultures":
		case "no_prof_loss_for_mercs":
		case "sea_repair":
		case "may_perform_slave_raid_on_same_religion":
		case "core_decay_on_your_own":
		case "elective_monarchy_add_buff":
		case "idea_claim_colonies":
		case "may_recruit_female_generals":
		case "own_coast_naval_combat_bonus":
		case "no_religion_penalty":
		case "may_establish_frontier":
		case "auto_explore_adjacent_to_colony":
			return capitalise(bonusValue);
		case "add_age_forcelimit_naval":
		case "advisor_pool":
		case "artillery_bonus_vs_fort":
		case "diplomatic_upkeep":
		case "diplomatic_reputation":
		case "colonists":
		case "diplomats":
		case "free_leader_pool":
		case "global_colonial_growth":
		case "governing_capacity":
		case "max_absolutism":
		case "merchants":
		case "missionaries":
		case "monarch_admin_power":
		case "monarch_diplomatic_power":
		case "monarch_military_power":
		case "monthly_splendor":
		case "naval_forcelimit":
		case "num_accepted_cultures":
		case "relation_with_heretics":
		case "siege_blockade_progress":
		case "years_of_nationalism":
		case "add_age_forcelimit_land":
		case "placed_merchant_power":
		case "free_policy":
		case "free_adm_policy":
		case "free_dip_policy":
		case "free_mil_policy":
		case "candidate_random_bonus":
		case "election_cycle":
		case "possible_policy":
		case "possible_adm_policy":
		case "possible_dip_policy":
		case "possible_mil_policy":
		case "min_autonomy_in_territories":
			return (+bonusValue).toFixed(0);
		case "add_age_authority":
		case "army_tradition":
		case "global_institution_growth":
		case "global_sailors":
		case "land_forcelimit":
		case "leader_land_fire":
		case "leader_land_manuever":
		case "leader_land_shock":
		case "leader_naval_fire":
		case "leader_naval_manuever":
		case "leader_naval_shock":
		case "leader_siege":
		case "reduced_liberty_desire":
			return (+bonusValue).toFixed(1);
		case "devotion":
		case "legitimacy":
		case "global_heretic_missionary_strength":
		case "global_unrest":
		case "horde_unity":
		case "imperial_authority_value":
		case "imperial_mandate":
		case "inflation_reduction":
		case "interest":
		case "meritocracy":
		case "monthly_militarized_society":
		case "navy_tradition":
		case "papal_influence":
		case "prestige":
		case "republican_tradition":
		case "tolerance_heathen":
		case "tolerance_heretic":
		case "tolerance_own":
		case "war_exhaustion":
		case "yearly_absolutism":
		case "yearly_corruption":
		case "monthly_piety":
		case "monthly_karma":
		case "prestige_per_development_from_conversion":
		case "cavalry_shock":
		case "infantry_shock":
		case "artillery_fire":
		case "infantry_fire":
		case "max_revolutionary_zeal":
		case "cavalry_fire":
		case "trade_goods_size":
		case "local_monthly_devastation":
			return (+bonusValue).toFixed(2);
		case "add_age_manpower":
		case "add_age_sailors":
		case "global_manpower":
			return (bonusValue) + " thousand";
		case "add_cb":
		case "decision":
		case "inflationreduction":
		case "add_stand":
			return bonusValue;
		default:
			var val = (+bonusValue)*100;
			return Number.isInteger(val) ? val.toFixed(0) + '%' : val.toFixed(2) + '%';
	}
}

function capitalise(s) {
    return s.substring(0,1).toUpperCase() + s.substring(1).toLowerCase();
}

function baseMap(bonusName){
    switch(bonusName){
    case "accept_vassalization_reasons":
		return "accept_vassalization_reasons";
	case "adm_advisor_cost":
		return "admin_advisor_cost";
	case "adm_tech_cost_modifier":
		return "administrative_technology_cost";
	case "administrative_efficiency":
		return "administrative_efficiency";
	case "admiral_cost":
		return "admiral_cost";
	case "adventurers_loyalty_modifier":
		return "adventurers_loyalty_modifier";
	case "advisor_cost":
		return "advisor_cost";
	case "advisor_pool":
		return "advisor_pool";
	case "ae_impact":
		return "aggressive_expansion_impact";
	case "all_power_cost":
		return "all_power_costs";
	case "allowed_marine_fraction":
		return "allowed_marine_fraction";
	case "amount_of_banners":
		return "amount_of_banners";
	case "army_tradition":
		return "yearly_army_tradition";
	case "army_tradition_decay":
		return "yearly_army_tradition_decay";
	case "army_tradition_from_battle":
		return "army_tradition_from_battle";
	case "artillery_bonus_vs_fort":
		return "artillery_bonus_vs_fort";
	case "artillery_cost":
		return "artillery_cost";
	case "artillery_fire":
		return "artillery_fire";
	case "artillery_power":
		return "artillery_combat_ability";
	case "auto_explore_adjacent_to_colony":
		return "auto-explore_adjacent_to_colony";
	case "autonomy_change_time":
		return "autonomy_change_cooldown";
	case "available_province_loot":
		return "available_province_loot";
	case "backrow_artillery_damage":
		return "artillery_damage_from_backrow";
	case "blockade_efficiency":
		return "blockade_efficiency";
	case "brahmins_hindu_loyalty_modifier":
		return "brahmins_hindu_loyalty_modifier";
	case "brahmins_muslim_loyalty_modifier":
		return "brahmins_muslim_loyalty_modifier";
	case "build_cost":
		return "construction_cost";
	case "build_time":
		return "construction_time";
	case "burghers_influence_modifier":
		return "burghers_influence_modifier";
	case "burghers_loyalty_modifier":
		return "burghers_loyalty_modifier";
	case "can_fabricate_for_vassals":
		return "can_fabricate_for_vassals";
	case "candidate_random_bonus":
		return "candidate_random_bonus";
	case "capture_ship_chance":
		return "ship_capture_chance";
	case "caravan_power":
		return "caravan_power";
	case "cav_to_inf_ratio":
		return "cavalry_to_infantry_ratio";
	case "cavalry_cost":
		return "cavalry_cost";
	case "cavalry_fire":
		return "cavalry_fire";
	case "cavalry_flanking":
		return "cavalry_flanking_ability";
	case "cavalry_power":
		return "cavalry_combat_ability";
	case "cavalry_shock":
		return "cavalry_shock";
	case "cb_on_overseas":
		return "cb_on_overseas";
	case "cb_on_primitives":
		return "cb_on_primitives";
	case "cb_on_religious_enemies":
		return "cb_on_religious_enemies";
	case "center_of_trade_upgrade_cost":
		return "center_of_trade_upgrade_cost";
	case "church_loyalty_modifier":
		return "church_loyalty_modifier";
	case "church_power_modifier":
		return "church_power_modifier";
	case "claim_duration":
		return "claim_duration";
	case "colonist_placement_chance":
		return "settler_chance";
	case "colonists":
		return "colonists";
	case "core_creation":
		return "core_creation_cost";
	case "core_decay_on_your_own":
		return "core_decay_on_your_own";
	case "culture_conversion_cost":
		return "culture_conversion_cost";
	case "curia_powers_cost":
		return "curia_powers_cost";
	case "defensiveness":
		return "fort_defense";
	case "development_cost":
		return "development_cost";
	case "devotion":
		return "yearly_devotion";
	case "dhimmi_loyalty_modifier":
		return "dhimmi_loyalty_modifier";
	case "dip_advisor_cost":
		return "diplomatic_advisor_cost";
	case "dip_tech_cost_modifier":
		return "diplomatic_technology_cost";
	case "diplomatic_annexation_cost":
		return "diplomatic_annexation_cost";
	case "diplomatic_reputation":
		return "diplomatic_reputation";
	case "diplomatic_upkeep":
		return "diplomatic_relations";
	case "diplomats":
		return "diplomats";
	case "discipline":
		return "discipline";
	case "discovered_relations_impact":
		return "discovered_relations_impact";
	case "disengagement_chance":
		return "ship_disengagement_chance";
	case "drill_decay_modifier":
		return "drill_decay_modifier";
	case "drill_gain_modifier":
		return "drill_gain_modifier";
	case "election_cycle":
		return "election_cycle";
	case "embargo_efficiency":
		return "embargo_efficiency";
	case "embracement_cost":
		return "institution_embracement_cost";
	case "enemy_core_creation":
		return "enemy_core_creation";
	case "enforce_religion_cost":
		return "enforce_religion_cost";
	case "envoy_travel_time":
		return "envoy_travel_time";
	case "expand_administration_cost":
		return "expand_administration_cost";
	case "expel_minorities_cost":
		return "expel_minorities_cost";
	case "extra_manpower_at_religious_war":
		return "extra_manpower_at_religious_war";
	case "fabricate_claims_cost":
		return "fabricate_claims_cost";
	case "female_advisor_chance":
		return "female_advisor_chance";
	case "fire_damage":
		return "land_fire_damage";
	case "fire_damage_received":
		return "fire_damage_received";
	case "flagship_cost":
		return "flagship_cost";
	case "fort_maintenance_modifier":
		return "fort_maintenance_modifier";
	case "free_adm_policy":
		return "free_administrative_policy";
	case "free_dip_policy":
		return "free_diplomatic_policy";
	case "free_leader_pool":
		return "leader(s)_without_upkeep";
	case "free_mil_policy":
		return "free_military_policy";
	case "free_policy":
		return "free_policy";
	case "galley_cost":
		return "galley_cost";
	case "galley_power":
		return "galley_combat_ability";
	case "garrison_size":
		return "garrison_size";
	case "general_cost":
		return "general_cost";
	case "global_autonomy":
		return "global_autonomy";
	case "global_colonial_growth":
		return "global_settler_increase";
	case "global_foreign_trade_power":
		return "trade_power_abroad";
	case "global_garrison_growth":
		return "national_garrison_growth";
	case "global_heretic_missionary_strength":
		return "missionary_strength_vs_heretics";
	case "global_institution_spread":
		return "institution_spread";
	case "global_manpower":
		return "national_manpower";
	case "global_manpower_modifier":
		return "national_manpower_modifier";
	case "global_missionary_strength":
		return "missionary_strength";
	case "global_naval_barrage_cost":
		return "naval_barrage_cost";
	case "global_naval_engagement_modifier":
		return "global_naval_engagement_modifier";
	case "global_own_trade_power":
		return "domestic_trade_power";
	case "global_prov_trade_power_modifier":
		return "provincial_trade_power_modifier";
	case "global_regiment_cost":
		return "regiment_cost";
	case "global_regiment_recruit_speed":
		return "regiment_recruit_speed";
	case "global_religious_conversion_resistance":
		return "global_religious_conversion_resistance";
	case "global_sailors":
		return "national_sailors";
	case "global_sailors_modifier":
		return "national_sailors_modifier";
	case "global_ship_cost":
		return "ship_cost";
	case "global_ship_recruit_speed":
		return "shipbuilding_time";
	case "global_ship_repair":
		return "global_ship_repair";
	case "global_ship_trade_power":
		return "ship_trade_power";
	case "global_spy_defence":
		return "global_spy_defence";
	case "global_supply_limit_modifier":
		return "supply_limit_modifier";
	case "global_tariffs":
		return "global_tariffs";
	case "global_tax_modifier":
		return "national_tax_modifier";
	case "global_trade_goods_size_modifier":
		return "goods_produced_modifier";
	case "global_trade_power":
		return "global_trade_power";
	case "global_unrest":
		return "national_unrest";
	case "governing_capacity":
		return "governing_capacity";
	case "governing_capacity_modifier":
		return "governing_capacity_modifier";
	case "harmonization_speed":
		return "harmonization_speed";
	case "harsh_treatment_cost":
		return "harsh_treatment_cost";
	case "heavy_ship_cost":
		return "heavy_ship_cost";
	case "heavy_ship_power":
		return "heavy_ship_combat_ability";
	case "heir_chance":
		return "chance_of_new_heir";
	case "horde_unity":
		return "yearly_horde_unity";
	case "hostile_attrition":
		return "hostile_attrition";
	case "idea_claim_colonies":
		return "idea_claim_colonies";
	case "idea_cost":
		return "idea_cost";
	case "imperial_authority":
		return "imperial_authority_modifier";
	case "imperial_authority_value":
		return "imperial_authority";
	case "imperial_mandate":
		return "imperial_mandate";
	case "improve_relation_modifier":
		return "improve_relations";
	case "infantry_cost":
		return "infantry_cost";
	case "infantry_fire":
		return "infantry_fire";
	case "infantry_power":
		return "infantry_combat_ability";
	case "infantry_shock":
		return "infantry_shock";
	case "inflation_action_cost":
		return "reduce_inflation_cost";
	case "inflation_reduction":
		return "yearly_inflation_reduction";
	case "innovativeness_gain":
		return "innovativeness_gain";
	case "institution_spread_from_true_faith":
		return "institution_spread_from_true_faith";
	case "interest":
		return "interest_per_annum";
	case "justify_trade_conflict_cost":
		return "justify_trade_conflict_cost";
	case "land_attrition":
		return "attrition";
	case "land_forcelimit":
		return "land_force_limit";
	case "land_forcelimit_modifier":
		return "land_force_limit_modifier";
	case "land_maintenance_modifier":
		return "land_maintenance_modifier";
	case "land_morale":
		return "morale_of_armies";
	case "leader_cost":
		return "leader_cost";
	case "leader_land_fire":
		return "land_leader_fire";
	case "leader_land_manuever":
		return "land_leader_manuever";
	case "leader_land_shock":
		return "land_leader_shock";
	case "leader_naval_fire":
		return "naval_leader_fire";
	case "leader_naval_manuever":
		return "naval_leader_manuever";
	case "leader_naval_shock":
		return "naval_leader_shock";
	case "leader_siege":
		return "leader_siege";
	case "legitimacy":
		return "yearly_legitimacy";
	case "liberty_desire_from_subject_development":
		return "liberty_desire_from_subjects_development";
	case "light_ship_cost":
		return "light_ship_cost";
	case "light_ship_power":
		return "light_ship_combat_ability";
	case "loot_amount":
		return "loot_amount";
	case "mages_loyalty_modifier":
		return "mages_loyalty_modifier";
	case "manpower_in_true_faith_provinces":
		return "manpower_in_true_faith_provinces";
	case "manpower_recovery_speed":
		return "manpower_recovery_speed";
	case "max_absolutism":
		return "maximum_absolutism";
	case "max_revolutionary_zeal":
		return "max_revolutionary_zeal";
	case "may_establish_frontier":
		return "may_establish_frontier";
	case "may_explore":
		return "may_explore";
	case "may_perform_slave_raid":
		return "may_raid_coasts";
	case "may_perform_slave_raid_on_same_religion":
		return "may_raid_coasts_(same_religion)";
	case "may_recruit_female_generals":
		return "may_recruit_female_generals";
	case "merc_maintenance_modifier":
		return "mercenary_maintenance";
	case "mercantilism_cost":
		return "mercantilism_cost";
	case "mercenary_cost":
		return "mercenary_cost";
	case "mercenary_discipline":
		return "mercenary_discipline";
	case "mercenary_manpower":
		return "mercenary_manpower";
	case "merchants":
		return "merchants";
	case "meritocracy":
		return "yearly_meritocracy";
	case "migration_cooldown":
		return "migration_cooldown";
	case "mil_advisor_cost":
		return "military_advisor_cost";
	case "mil_tech_cost_modifier":
		return "military_technology_cost";
	case "min_autonomy_in_territories":
		return "minimum_autonomy_in_territories";
	case "missionaries":
		return "missionaries";
	case "missionary_maintenance_cost":
		return "missionary_maintenance_cost";
	case "monarch_admin_power":
		return "monarch_admininstrative_power";
	case "monarch_diplomatic_power":
		return "monarch_diplomatic_power";
	case "monarch_military_power":
		return "monarch_military_power";
	case "monthly_fervor_increase":
		return "monthly_fervor_increase";
	case "monthly_karma":
		return "monthly_karma";
	case "monthly_militarized_society":
		return "monthly_militarized_society";
	case "monthly_piety":
		return "monthly_piety";
	case "monthly_splendor":
		return "monthly_splendor";
	case "movement_speed":
		return "movement_speed";
	case "movement_speed_onto_off_boat_modifier":
		return "movement_speed_onto_off_boat_modifier";
	case "native_assimilation":
		return "native_assimilation";
	case "native_uprising_chance":
		return "native_uprising_chance";
	case "naval_attrition":
		return "naval_attrition";
	case "naval_forcelimit":
		return "naval_force_limit";
	case "naval_forcelimit_modifier":
		return "naval_force_limit_modifier";
	case "naval_maintenance_modifier":
		return "naval_maintenance_modifier";
	case "naval_morale":
		return "morale_of_navies";
	case "naval_tradition_from_trade":
		return "naval_tradition_from_trade";
	case "navy_tradition":
		return "yearly_navy_tradition";
	case "navy_tradition_decay":
		return "yearly_navy_tradition_decay";
	case "no_religion_penalty":
		return "no_religion_penalty";
	case "nobles_loyalty_modifier":
		return "nobles_loyalty_modifier";
	case "num_accepted_cultures":
		return "num_accepted_cultures";
	case "own_coast_naval_combat_bonus":
		return "own_coast_naval_combat_bonus";
	case "papal_influence":
		return "papal_influence";
	case "placed_merchant_power":
		return "placed_merchant_power";
	case "possible_adm_policy":
		return "possible_admin_policy";
	case "possible_condottieri":
		return "possible_condottieri";
	case "possible_dip_policy":
		return "possible_diplomatic_policy";
	case "possible_mil_policy":
		return "possible_military_policy";
	case "possible_policy":
		return "possible_policy";
	case "power_projection_from_insults":
		return "power_projection_from_insults";
	case "prestige":
		return "yearly_prestige";
	case "prestige_decay":
		return "prestige_decay";
	case "prestige_from_land":
		return "prestige_from_land_battles";
	case "prestige_from_naval":
		return "prestige_from_naval_battles";
	case "prestige_per_development_from_conversion":
		return "prestige_per_development_from_missionary";
	case "privateer_efficiency":
		return "privateer_efficiency";
	case "production_efficiency":
		return "production_efficiency";
	case "promote_culture_cost":
		return "promote_culture_cost";
	case "province_warscore_cost":
		return "province_war_score_cost";
	case "range":
		return "colonial_range";
	case "raze_power_gain":
		return "razing_power_gain";
	case "rebel_support_efficiency":
		return "rebel_support_efficiency";
	case "recover_army_morale_speed":
		return "recover_army_morale_speed";
	case "recover_navy_morale_speed":
		return "recover_navy_morale_speed";
	case "reduced_liberty_desire":
		return "liberty_desire_in_subjects";
	case "reduced_liberty_desire_on_same_continent":
		return "liberty_desire_in_same_continent_subjects";
	case "reduced_stab_impacts":
		return "reduced_stab_impacts";
	case "reelection_cost":
		return "reelection_cost";
	case "reform_progress_growth":
		return "reform_progress_growth";
	case "reinforce_cost_modifier":
		return "reinforce_cost";
	case "reinforce_speed":
		return "reinforce_speed";
	case "relation_with_heretics":
		return "relation_with_heretics";
	case "religious_unity":
		return "religious_unity";
	case "republican_tradition":
		return "yearly_republican_tradition";
	case "reserves_organisation":
		return "reserves_organisation";
	case "rival_border_fort_maintenance":
		return "fort_maintenance_on_border_with_rival";
	case "sailor_maintenance_modifer":
		return "sailor_maintenance";
	case "sailors_recovery_speed":
		return "sailor_recovery_speed";
	case "same_culture_advisor_cost":
		return "same_culture_advisor_cost";
	case "sea_repair":
		return "sea_repair";
	case "ship_durability":
		return "ship_durability";
	case "ship_power_propagation":
		return "ship_trade_power_propagation";
	case "shock_damage":
		return "shock_damage";
	case "shock_damage_received":
		return "shock_damage_received";
	case "siege_ability":
		return "siege_ability";
	case "siege_blockade_progress":
		return "siege_blockade_progress";
	case "special_unit_forcelimit":
		return "special_unit_force_limit";
	case "spy_offence":
		return "spy_network_construction";
	case "stability_cost_modifier":
		return "stability_cost_modifier";
	case "stability_cost_to_declare_war":
		return "stability_cost_to_declare_war";
	case "state_maintenance_modifier":
		return "state_maintenance_modifier";
	case "sunk_ship_morale_hit_recieved":
		return "sunk_ship_morale_hit_recieved";
	case "supply_limit_modifier":
		return "supply_limit_modifier";
	case "technology_cost":
		return "technology_cost";
	case "tolerance_heathen":
		return "tolerance_heathen";
	case "tolerance_heretic":
		return "tolerance_heretic";
	case "tolerance_own":
		return "tolerance_of_the_true_faith";
	case "trade_company_governing_cost":
		return "trade_company_governing_cost";
	case "trade_company_investment_cost":
		return "trade_company_investment_cost";
	case "trade_efficiency":
		return "trade_efficiency";
	case "trade_range_modifier":
		return "trade_range";
	case "trade_steering":
		return "trade_steering";
	case "transport_cost":
		return "transport_cost";
	case "transport_power":
		return "transport_combat_ability";
	case "unjustified_demands":
		return "unjustified_demands";
	case "vaisyas_loyalty_modifier":
		return "vaisyas_loyalty_modifier";
	case "vassal_forcelimit_bonus":
		return "vassal_force_limit_contribution";
	case "vassal_income":
		return "income_from_vassals";
	case "war_exhaustion":
		return "war_exhaustion";
	case "war_exhaustion_cost":
		return "cost_of_reducing_war_exhaustion";
	case "war_taxes_cost_modifier":
		return "war_taxes_cost";
	case "warscore_cost_vs_other_religion":
		return "war_score_cost_vs_other_religion";
	case "yearly_absolutism":
		return "yearly_absolutism";
	case "yearly_army_professionalism":
		return "yearly_army_professionalism";
	case "yearly_corruption":
		return "yearly_corruption";
	case "yearly_harmony":
		return "yearly_harmony";
	case "yearly_patriarch_authority":
		return "yearly_patriarch_authority";
	case "yearly_tribal_allegiance":
		return "yearly_tribal_allegiance";
	case "years_of_nationalism":
		return "years_of_separatism";
	default:
		return bonusName;
    }
}